bulliby_chat:
    resource: "@BullibyChatBundle/Controller/"
    type:     annotation
    prefix:   /chat

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

bulliby_user:
    resource: "@BullibyUserBundle/Controller/"
    type:     annotation
    prefix:   /user
