security:
     providers:
         custom_provider:
            entity:
                class: AppBundle:User

     encoders:
         AppBundle\Entity\User:    
            algorithm: bcrypt
            cost: 12

     firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login: 
                login_path: login
                check_path: login
            guard:
                authenticators:
                     - bulliby.form_authenticator
